# Generated by Django 4.1.1 on 2024-07-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_customer_remove_orderproduct_order_and_more'),
        ('accounts', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_of_creation', 'profile__user__last_name', 'profile__user__first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_order', to='store.product')),
            ],
            options={
                'ordering': ['order__date_of_creation', 'product__title'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounts.profile'),
        ),
    ]
