# Generated by Django 4.1.1 on 2024-07-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_customer_remove_orderproduct_order_and_more'),
        ('accounts', '0006_profileproduct_remove_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='is_in', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containing', to='accounts.profile')),
            ],
            options={
                'ordering': ['product__title'],
            },
        ),
        migrations.DeleteModel(
            name='ProfileProduct',
        ),
    ]
