# Generated by Django 4.1.1 on 2024-07-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_userproduct_options_alter_userproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containing', to=settings.AUTH_USER_MODEL),
        ),
    ]
