# Generated by Django 4.1.1 on 2024-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
