# Generated by Django 4.1.1 on 2024-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_order_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
