# Generated by Django 4.1.1 on 2024-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_order_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
